### ISSUE TITLE
Pros and cons compared to ANGLE? 

### ISSUE THREAD

**Issue by LifeIsStrange** [NVIDIAGameWorks/nvrhi#1]

**Comment by apanteleev** [comment]
I have not used ANGLE. But from a quick look, it appears that ANGLE is a translator from GLES 3 to various other APIs. In contrast with that, NVRHI has a custom interface that is designed to map reasonably well to DX12 and Vulkan, and that includes modern features such as resource tables, bindless resources, ray tracing, and meshlets. NVRHI also provides a custom validation layer to catch more high-level problems with user code.

IOW, they solve different problems: ANGLE is designed to make GLES code work on other APIs, while NVRHI is designed to allow quick development of new portable graphics code using modern features.

**Comment by LifeIsStrange** [comment]
Interesting, so that's more in the spirit of oneAPI https://www.oneapi.io/ but if I understand (?) oneAPI is more for compute while this is for graphics.
https://github.com/gfx-rs/gfx also comes to mind but is language specific.
Anyway, useful project, thanks for open sourcing!

**Comment by eugeneko** [comment]
@apanteleev It's me again, and I am quite confused by this repo and https://github.com/NVIDIAGameWorks/NRI.

I initially assumed that NVIDIAGameWorks is coordinated by NVidia. Now I am confused why there are two so similar APIs, what are the end goals for these projects, and whether to expect future maintenance.

Do you maybe know an answer, or maybe you can redirect me to more appropriate place to ask?

**Comment by apanteleev** [comment]
@eugeneko 
These libraries are indeed very similar, and actually have a common ancestor, but they were developed by different teams that had different vision. NVRHI is more about convenience and safety, while NRI provides a lower-level abstraction, therefore having lower CPU overhead but requiring more verbose code on the application side. Sort of like DX11 vs DX12.
