### ISSUE TITLE
Add documentation on the GPU read-back process to the docs (texture/buffer/etc)

### ISSUE THREAD

**Issue by JSandusky** [NVIDIAGameWorks/nvrhi#11]
Although readback at runtime is generally bad, critical readback tasks include saving results of cubemap convolution for IBL and other compute related tasks that may be done offline.

Doesn't need to by hyper detailed documentation, just a basic block of "_you can grab a layer/mip like this and buffers are done like this_." Utility functions are certainly welcome, but this is about docs.

**Comment by apanteleev** [comment]
Addressed in https://github.com/NVIDIAGameWorks/nvrhi/commit/c0a162a3bcc6ca74f143a5d20db4322b5cef7536 

Some fixes and improvements were made while writing the documentation, so thank you for the suggestion.
