### ISSUE TITLE
Typo in header

### ISSUE THREAD

**Issue by manuelk** [NVIDIAGameWorks/nvrhi#12]
https://github.com/NVIDIAGameWorks/nvrhi/blob/main/include/nvrhi/nvrhi.h#L1386
(and next line too)

'prefer' - not 'perfer'

**Comment by apanteleev** [comment]
Fixed in https://github.com/NVIDIAGameWorks/nvrhi/commit/f9b72da9464790f17e7445cd9fd34649251a74a5
Closing
