### ISSUE TITLE
PSO recreation on frame buffer resize

### ISSUE THREAD

**Issue by vancerm** [NVIDIAGameWorks/nvrhi#22]
I'm confused why the validation layer enforces PSO framebuffer sizes to match a framebuffer binding. The rest of the member checks are correct, but I don't believe size needs to be the same. Recreating PSOs due to a window resize can be a very expensive operation. The documentation mentions:

"Following the Vulkan API for creating graphics pipelines, NVRHI has a concept of a framebuffer. A framebuffer is a collection of render targets, up to 8, and a depth target, each with its subresource set. Framebuffers hold strong references to their textures and are immutable.

A valid framebuffer is necessary to create a graphics or meshlet pipeline. A pipeline created with a certain framebuffer can then be used with the same framebuffer, or with any other framebuffer which is compatible. Two framebuffers are considered compatible when they have the same number and formats of the render targets, and the width and height of the render targets."

I believe this is meant to follow Vulkan render pass compatibility (note render pass, not framebuffer). The Vulkan docs don't mention the size (width and height) in the compatibility requirements: https://registry.khronos.org/vulkan/specs/1.2-extensions/html/chap8.html#renderpass-compatibility

Removing this validation and reusing PSOs with a resized framebuffer doesn't trigger any validation issues on d3d12 or VK. If I'm incorrect can you point me to the relevant documentation for d3d12 or VK?

Thanks!

**Comment by apanteleev** [comment]
Thank you for reporting this issue. Upon closer inspection, we were also confused about the origins of this restriction. I've removed it and added a new `FramebufferInfoEx` struct to make porting existing code that uses the `width` and `height` members easier.
