### ISSUE TITLE
Add Third-party projects section to readme

### ISSUE THREAD

**Issue by vbyrd** [NVIDIAGameWorks/nvrhi#33]
It would be nice to discover third-party open-source projects implementing NVRHI. I think it would help with adoption of NVRHI in more projects. 

Example: 
[Robert Beckebans Doom 3 BFG Port](https://github.com/RobertBeckebans/RBDOOM-3-BFG) recently implemented NVRHI to replace OpenGL.

**Comment by apanteleev** [comment]
Thank you for the suggestion, I think it's a good idea.
But do you know of any other notable open-source NVRHI-based projects, besides RBDoom3-BFG? I could only find some small experiments, and it would be nice to list more than one.

**Comment by vbyrd** [comment]
Indeed a Github search doesn't reveal many open-source projects ([nvrhi -org:RobertBeckebans -org:NVIDIAGameWorks](https://github.com/search?q=nvrhi+-org%3ARobertBeckebans+-org%3ANVIDIAGameWorks&type=commits)) outside of testing and small projects. I suppose one example is better than nothing.

**Comment by apanteleev** [comment]
Added RBDoom3 and some NVIDIA projects for completeness.
Closing.

**Comment by RobertBeckebans** [comment]
Thanks for mentioning my project. There is a small typo above: NVHRI instead of NVRHI.

**Comment by apanteleev** [comment]
🤦 Fixed, thank you.
