### ISSUE TITLE
Depth texture read/write transitions

### ISSUE THREAD

**Issue by f6cd** [NVIDIAGameWorks/nvrhi#34]
I'm adding transparent textures to my engine. To go about this, I'm drawing transparent meshes with depth write disabled. Initially I was just disabled the depth writing on the `GraphicsState` - however this throw a warning about being unoptimal.

I have a color and depth texture. The depth texture is created in the `DepthWrite` state, with `keepInitialState` enabled. At initialization, two framebuffers are created, identical except `framebufferDesc.depthAttachment.isReadOnly` is true/false. For each framebuffer, a corresponding pipeline is created, with `setDepthWriteEnable` set accordingly.

At draw, the correct pipeline & framebuffer is added to the graphics state depending on if the material is transparent, and is dispatched.

All opaque objects are drawn first (obviously using the pipeline expecting `DepthWrite` of the depth texture). Then, all transparent objects. The first time a transparent object is drawn per frame, I get this warning:
```
[Vulkan: location=1303270965 code=0, layerPrefix='Validation'] Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object 0: handle = 0x3b19d147850, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x4dae5635 | vkQueueSubmit(): pSubmits[0].pCommandBuffers[0] command buffer VkCommandBuffer 0x3b19d147850[] expects VkImage 0xe694900000000278[] (subresource: aspectMask 0x2 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL--instead, current layout is VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL.
```
I have automatic barriers enabled. I must have made a mistake somewhere, because NVRHI is intended to take care of these transitions. As there's no further errors, it must, just not immediately. I can attach a renderdoc capture if it helps. Thanks!

**Comment by f6cd** [comment]
Still trying to figure this out. 

The error occurs in the `setGraphicsState` method of the `CommandList`. With automatic barriers turned on, the `trackResourcesAndBarriers` method should transition the depth attachment to the correct state. Stepping through the method, I'm certain that the correct transition calls are being made in higher-level-user-land. 

I've attempted a few different things...
* Disabling `KeepInitialState` on the depth texture, and manually transitioning the state with `SetTextureState` + `CommitBarriers` each frame.
* Explicitly tracking the state with `beginTrackingTextureState` + the above.
* The above, with `KeepInitialState` enabled.
* Split the opaque and transparent calls by closing + submitting + reopening the `CommandList`.
I believe these are all redundant when `AutomaticBarriers` is enabled on the `CommandList`, as texture layouts are cached & only transitioned when necessary.

Not sure what else to attempt. There's no warnings thrown by the NVRHI validation layer, which makes me think it may be a bug somewhere in the Vulkan implementation. Unfortunately I don't support DX12/11, so I can't test this. I'm assuming the Donut samples and RBDOOM3 implement something similar - neither throw this error. Unfortunately both are shrouded in abstraction, and I can't tell what they're doing differently. I'd be happy to share a Renderdoc capture - or even all of my source code..!

```
[Frame: 0
[WARN]  [Vulkan: location=0x2c8c6e7d code=0, layerPrefix='Validation'] Validation Error: [ VUID-VkImageMemoryBarrier2-oldLayout-01197 ] Object 0: handle = 0x44d6b07c850, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x2c8c6e7d | vkCmdPipelineBarrier2(): .pImageMemoryBarriers[1] VkImage 0xb8a5a300000001b3[] cannot transition the layout of aspect=2 level=0 layer=0 from VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL when the previous known layout is VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL. The Vulkan spec states: If srcQueueFamilyIndex and dstQueueFamilyIndex define a queue family ownership transfer or oldLayout and newLayout define an image layout transition, oldLayout must be VK_IMAGE_LAYOUT_UNDEFINED or the current layout of the image subresources affected by the barrier (https://vulkan.lunarg.com/doc/view/1.3.243.0/linux/1.3-extensions/vkspec.html#VUID-VkImageMemoryBarrier2-oldLayout-01197)
[WARN]  [Vulkan: location=0x4dae5635 code=0, layerPrefix='Validation'] Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object 0: handle = 0x44d6b07c850, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x4dae5635 | vkQueueSubmit(): pSubmits[0].pCommandBuffers[0] command buffer VkCommandBuffer 0x44d6b07c850[] expects VkImage 0xb8a5a300000001b3[] (subresource: aspectMask 0x2 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL--instead, current layout is VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL.
```
```
Frame: 1
[WARN]  [Vulkan: location=0x4dae5635 code=0, layerPrefix='Validation'] Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object 0: handle = 0x44d5f34c850, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x4dae5635 | vkQueueSubmit(): pSubmits[0].pCommandBuffers[0] command buffer VkCommandBuffer 0x44d5f34c850[] expects VkImage 0xb8a5a300000001b3[] (subresource: aspectMask 0x2 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL--instead, current layout is VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL.
[WARN]  [Vulkan: location=0x2c8c6e7d code=0, layerPrefix='Validation'] Validation Error: [ VUID-VkImageMemoryBarrier2-oldLayout-01197 ] Object 0: handle = 0x44d6ac86450, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x2c8c6e7d | vkCmdPipelineBarrier2(): .pImageMemoryBarriers[1] VkImage 0xb8a5a300000001b3[] cannot transition the layout of aspect=2 level=0 layer=0 from VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL when the previous known layout is VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL. The Vulkan spec states: If srcQueueFamilyIndex and dstQueueFamilyIndex define a queue family ownership transfer or oldLayout and newLayout define an image layout transition, oldLayout must be VK_IMAGE_LAYOUT_UNDEFINED or the current layout of the image subresources affected by the barrier (https://vulkan.lunarg.com/doc/view/1.3.243.0/linux/1.3-extensions/vkspec.html#VUID-VkImageMemoryBarrier2-oldLayout-01197)
[WARN]  [Vulkan: location=0x4dae5635 code=0, layerPrefix='Validation'] Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object 0: handle = 0x44d6ac86450, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x4dae5635 | vkQueueSubmit(): pSubmits[0].pCommandBuffers[0] command buffer VkCommandBuffer 0x44d6ac86450[] expects VkImage 0xb8a5a300000001b3[] (subresource: aspectMask 0x2 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL--instead, current layout is VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL.
```

**Comment by RobertBeckebans** [comment]
What helped me with porting RBDOOM-3-BFG to NVHRI was to analyse the RenderDoc shots of Donut.
You can also do this with my engine if you start it in RenderDoc with the arguments +set r_logLevel 2. Then you also get the debug shader markers and you can look for Render_GenericShaderPasses. It is idRenderBackend::DrawGenericPasses() in the code. That's where all the generic materials for Quake 3 style blend effects are rendered. The depth buffer is usually only written in the early-z pass at the beginning of the frame and not in that function.

However we also don't set the a second depth image attachement as read-only and have several warnings that aren't really resolved: https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/760

I hope this helps a bit.

**Comment by apanteleev** [comment]
It looks like `VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL` is just not implemented properly on the NVRHI side.

Can you try replacing line 279 in `vulkan-constants.cpp` with this one? 

```
            vk::ImageLayout::eDepthStencilReadOnlyOptimal },
```

**Comment by f6cd** [comment]
@apanteleev Thanks, this fixes the issue! With my initial setup of one command list + no manual resource tracking, there are no validation errors. Merely a copy+paste mistake, I'll close this now.

@RobertBeckebans Thanks for the pointers! I'll take another look, I did glean a lot last time (and stole your `BindingCache` class). I'll likely want a Z pre-pass too eventually.
