### ISSUE TITLE
Incomplete Vulkan HPP Initialization in DLL Builds

### ISSUE THREAD

**Issue by Aeva** [NVIDIAGameWorks/nvrhi#4]
I found a problem in the Vulkan backend while attempting to follow [the tutorial](https://github.com/NVIDIAGameWorks/nvrhi/blob/main/doc/Tutorial.md).  I built NVRHI for win64 from a fresh clone of the main branch like so:
```sh
cmake -D NVRHI_BUILD_SHARED=ON -D NVRHI_WITH_VULKAN=ON -D NVRHI_WITH_DX11=OFF -D NVRHI_WITH_DX12=OFF -D NVRHI_WITH_SHADER_COMPILER=OFF ..
```

The problem is, when I call `nvrhi::vulkan::createDevice` only calls the first of the three required `VULKAN_HPP_DEFAULT_DISPATCHER.init` variants, which means only `vkCreateInstance`, `vkEnumerateInstanceExtensionProperties`, `vkEnumerateInstanceLayerProperties`, and `vkEnumerateInstanceVersion` are initialized.  NVRHI then proceeds to behave as if the full initialization had been performed, and then immediately crashes when it tries to call `VULKAN_HPP_DEFAULT_DISPATCHER::createSemaphore` via `vk::Device::createSemaphore`, which is still null.

When `NVRHI_SHARED_LIBRARY_BUILD` is set, as is the case in my build, NVRHI defines `VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE` but not `VULKAN_HPP_STORAGE_SHARED` or `VULKAN_HPP_STORAGE_SHARED_EXPORT`.  According to [the vulkan-hpp docs](https://github.com/KhronosGroup/Vulkan-Hpp/blob/master/README.md#extensions--per-device-function-pointers), this means I can't just finish up the initialization in my own application.

So I think to fix this correctly, `VULKAN_HPP_STORAGE_SHARED` and `VULKAN_HPP_STORAGE_SHARED_EXPORT` need to be define for the build config or so, and nvrhi::vulkan::createDevice needs to be updated to initialize like so:
```c++
    DeviceHandle createDevice(const DeviceDesc& desc)
    {
#if defined(NVRHI_SHARED_LIBRARY_BUILD)
        const vk::DynamicLoader dl;
        const PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr =   // NOLINT(misc-misplaced-const)
            dl.getProcAddress<PFN_vkGetInstanceProcAddr>("vkGetInstanceProcAddr");
        VULKAN_HPP_DEFAULT_DISPATCHER.init(vkGetInstanceProcAddr);
        VULKAN_HPP_DEFAULT_DISPATCHER.init(desc.instance);
        VULKAN_HPP_DEFAULT_DISPATCHER.init(desc.device);
#endif
```

**Comment by apanteleev** [comment]
Changes implemented, thank you!
Is it working now? Unfortunately I don't have any test app configured to use NVRHI as a shared library at the moment.

**Comment by Aeva** [comment]
I'll try it out tonight and let you know

**Comment by Aeva** [comment]
Looks good!  Thanks so much!
