### ISSUE TITLE
Vulkan's CommandList::copyTexture copies the entire region instead of slice.

### ISSUE THREAD

**Issue by 01Pollux** [NVIDIAGameWorks/nvrhi#41]
`copyTexture(ITexture* _dst, const TextureSlice& dstSlice, IStagingTexture* _src, const TextureSlice& srcSlice)` and `copyTexture(IStagingTexture* _dst, const TextureSlice& dstSlice, ITexture* _src, const TextureSlice& srcSlice)` uses `vk::Extent3D srcMipSize/dstMipSize` of the whole image instead of the slice that was resolved.

https://github.com/NVIDIAGameWorks/nvrhi/blob/99396539ea7f2e9c9858c1e737c81cbd96866b4d/src/vulkan/vulkan-staging-texture.cpp#L180-L182

https://github.com/NVIDIAGameWorks/nvrhi/blob/99396539ea7f2e9c9858c1e737c81cbd96866b4d/src/vulkan/vulkan-staging-texture.cpp#L229-L231

was this the intended behaviour?

**Comment by apanteleev** [comment]
This was a bug, now fixed. Thank you for reporting it!
