### ISSUE TITLE
_SNORM format should be signed format in format-info.cpp

### ISSUE THREAD

**Issue by BlurryLight** [NVIDIAGameWorks/nvrhi#43]
https://github.com/NVIDIAGameWorks/nvrhi/blob/0884149e43e8e1aa9b0bb2f6ea36122b8cb3f9ad/src/common/format-info.cpp#L34C8-L34C147
![image](https://github.com/NVIDIAGameWorks/nvrhi/assets/14940338/bfc6be0e-d81e-477e-872e-6803ca6659f1)

I noticed all `_SNORM` formats have `false` label in `signed` column of the `c_FormatInfo`. `_SNORM` can be negative and as the name suggests, `Signed Normalization`. 

I'm not sure if it's a copy-paste typo or a weired design.

**Comment by apanteleev** [comment]
This was a copy-paste typo, now fixed for all `SNORM` formats. Thanks for reporting it!
