### ISSUE TITLE
Linking nvrhi and nvrhi_vk to a library produces errors when linking to an executable afterwards

### ISSUE THREAD

**Issue by tlegoc** [NVIDIAGameWorks/nvrhi#48]
Hi,
I followed the instruction to install nvrhi as a submodule and I'm trying to use it with cmake.
I use 
```cmake
set(NVRHI_WITH_VULKAN ON)
add_subdirectory(thirdparty/nvrhi)
```
To include the project, then later on I link it to one of my libraries.
```cmake
target_link_libraries(Renderer Vulkan-Headers) # This line changed a lot
target_link_libraries(Renderer nvrhi_vk)
target_link_libraries(Renderer nvrhi)
```
This is what it currently looks like. At some point I had nvrhi first, then I used `Vulkan::Vulkan` instead of `Vulkan-Headers`, etc. But in the end the target Renderer always built itself correctly.

Now if I link Renderer to another target and use one of the functions I get a link error LNK2001 (The compiler can't find vulkan-hpp's dynamic loader).

I tried linking nvrhi to said target, I tried linking vulkan, didn't work. Note that I use [vk-boostrap](https://github.com/charles-lunarg/vk-bootstrap) to speed up vulkan instance creation but even if I remove it it still doesn't work.

Does anyone have an idea as why it doesn't work ? Maybe I'm just dumb and forgot how c++ libraries and linking work.

**Comment by tlegoc** [comment]
Bonus code : how I include the headers
### In my library

VulkanContext.h
```cpp
#include <nvrhi/nvrhi.h>
#include <VkBootstrap.h>
```

VulkanContext.cpp
```cpp
#include <Renderer/VulkanContext.h>

#include <nvrhi/vulkan.h>
#include <nvrhi/validation.h>
#include <Logging/Logging.h>

#define GLFW_INCLUDE_VULKAN // Might not be needed, or maybe use GLFW_INCLUDE_NONE
#include <GLFW/glfw3.h>
```

### In my executable
TestContext.cpp
```cpp
#include <Renderer/VulkanContext.h>
```

**Comment by apanteleev** [comment]
> I get a link error LNK2001 (The compiler can't find vulkan-hpp's dynamic loader).

That's the problem. When linking NVRHI statically, some other part of the final linked program needs to define the Vulkan dynamic loader that will be used by NVRHI. When NVRHI is built as a DLL, the loader is defined inside the library.

See https://github.com/NVIDIAGameWorks/donut/blob/main/src/app/vulkan/DeviceManager_VK.cpp and search for "dynamic" for an example.

(Also, maybe it makes sense to add a CMake option to let NVRHI define the loader even in static linking mode)

**Comment by tlegoc** [comment]
> > I get a link error LNK2001 (The compiler can't find vulkan-hpp's dynamic loader).
> 
> That's the problem. When linking NVRHI statically, some other part of the final linked program needs to define the Vulkan dynamic loader that will be used by NVRHI. When NVRHI is built as a DLL, the loader is defined inside the library.
> 
> See https://github.com/NVIDIAGameWorks/donut/blob/main/src/app/vulkan/DeviceManager_VK.cpp and search for "dynamic" for an example.

Makes sense, I think I'll go towards the shared dll route.

> (Also, maybe it makes sense to add a CMake option to let NVRHI define the loader even in static linking mode)

What do you mean by that though?

Thanks a lot for the quick answer!

**Comment by apanteleev** [comment]
> What do you mean by that though?

I mean that I could add an option to change the way NVRHI is built in the static library mode. With the new option enabled, it would define the dynamic loader inside the library so that you won't have to. One downside here is that the application may need to use the dynamic loader before NVRHI is initialized, which would not be possible.

**Comment by tlegoc** [comment]
Ah I see. I'm not experienced enough to speak on the matter, I have to admit. 
I'm closing the issue, thanks again !
