### ISSUE TITLE
Unresolved external symbols

### ISSUE THREAD

**Issue by casool** [NVIDIAGameWorks/nvrhi#50]
I'm unable to build my project upon including this create device line in my code:
```c++
#include <nvrhi/vulkan.h>
...
nvrhi::vulkan::createDevice(deviceDesc);
...
```

```
1>main.cpp
1>nvrhi_vk.lib(vulkan-resource-bindings.obj) : error LNK2001: unresolved external symbol "class vk::DispatchLoaderDynamic vk::defaultDispatchLoaderDynamic" (?defaultDispatchLoaderDynamic@vk@@3VDispatchLoaderDynamic@1@A)
1>nvrhi_vk.lib(vulkan-commandlist.obj) : error LNK2001: unresolved external symbol "class vk::DispatchLoaderDynamic vk::defaultDispatchLoaderDynamic" (?defaultDispatchLoaderDynamic@vk@@3VDispatchLoaderDynamic@1@A)
1>nvrhi_vk.lib(vulkan-state-tracking.obj) : error LNK2001: unresolved external symbol "class vk::DispatchLoaderDynamic vk::defaultDispatchLoaderDynamic" (?defaultDispatchLoaderDynamic@vk@@3VDispatchLoaderDynamic@1@A)
1>nvrhi_vk.lib(vulkan-graphics.obj) : error LNK2001: unresolved external symbol "class vk::DispatchLoaderDynamic vk::defaultDispatchLoaderDynamic" (?defaultDispatchLoaderDynamic@vk@@3VDispatchLoaderDynamic@1@A)
1>nvrhi_vk.lib(vulkan-compute.obj) : error LNK2001: unresolved external symbol "class vk::DispatchLoaderDynamic vk::defaultDispatchLoaderDynamic" (?defaultDispatchLoaderDynamic@vk@@3VDispatchLoaderDynamic@1@A)
1>nvrhi_vk.lib(vulkan-meshlets.obj) : error LNK2001: unresolved external symbol "class vk::DispatchLoaderDynamic vk::defaultDispatchLoaderDynamic" (?defaultDispatchLoaderDynamic@vk@@3VDispatchLoaderDynamic@1@A)
1>nvrhi_vk.lib(vulkan-raytracing.obj) : error LNK2001: unresolved external symbol "class vk::DispatchLoaderDynamic vk::defaultDispatchLoaderDynamic" (?defaultDispatchLoaderDynamic@vk@@3VDispatchLoaderDynamic@1@A)
1>nvrhi_vk.lib(vulkan-staging-texture.obj) : error LNK2001: unresolved external symbol "class vk::DispatchLoaderDynamic vk::defaultDispatchLoaderDynamic" (?defaultDispatchLoaderDynamic@vk@@3VDispatchLoaderDynamic@1@A)
1>nvrhi_vk.lib(vulkan-buffer.obj) : error LNK2001: unresolved external symbol "class vk::DispatchLoaderDynamic vk::defaultDispatchLoaderDynamic" (?defaultDispatchLoaderDynamic@vk@@3VDispatchLoaderDynamic@1@A)
1>nvrhi_vk.lib(vulkan-shader.obj) : error LNK2001: unresolved external symbol "class vk::DispatchLoaderDynamic vk::defaultDispatchLoaderDynamic" (?defaultDispatchLoaderDynamic@vk@@3VDispatchLoaderDynamic@1@A)
1>nvrhi_vk.lib(vulkan-queries.obj) : error LNK2001: unresolved external symbol "class vk::DispatchLoaderDynamic vk::defaultDispatchLoaderDynamic" (?defaultDispatchLoaderDynamic@vk@@3VDispatchLoaderDynamic@1@A)
1>nvrhi_vk.lib(vulkan-device.obj) : error LNK2001: unresolved external symbol "class vk::DispatchLoaderDynamic vk::defaultDispatchLoaderDynamic" (?defaultDispatchLoaderDynamic@vk@@3VDispatchLoaderDynamic@1@A)
1>nvrhi_vk.lib(vulkan-queue.obj) : error LNK2001: unresolved external symbol "class vk::DispatchLoaderDynamic vk::defaultDispatchLoaderDynamic" (?defaultDispatchLoaderDynamic@vk@@3VDispatchLoaderDynamic@1@A)
1>nvrhi_vk.lib(vulkan-allocator.obj) : error LNK2001: unresolved external symbol "class vk::DispatchLoaderDynamic vk::defaultDispatchLoaderDynamic" (?defaultDispatchLoaderDynamic@vk@@3VDispatchLoaderDynamic@1@A)
1>nvrhi_vk.lib(vulkan-texture.obj) : error LNK2001: unresolved external symbol "class vk::DispatchLoaderDynamic vk::defaultDispatchLoaderDynamic" (?defaultDispatchLoaderDynamic@vk@@3VDispatchLoaderDynamic@1@A)
```

My top level CMakeLists:
```cmake
...
# Dependencies
find_package(Vulkan REQUIRED)
add_subdirectory(Dependencies)

if (VULKAN_FOUND)
    include_directories(${Vulkan_INCLUDE_DIRS})
    target_link_libraries (${PROJECT_NAME} ${Vulkan_LIBRARIES} Dependencies)
endif (VULKAN_FOUND)
...
```

Dependencies/CMakeLists:
```cmake
...
set(NVRHI_BUILD_SHARED OFF CACHE BOOL "" FORCE)

set(NVRHI_WITH_DX11 OFF CACHE BOOL "" FORCE)
set(NVRHI_WITH_DX12 OFF CACHE BOOL "" FORCE)
set(NVRHI_WITH_VULKAN ON CACHE BOOL "" FORCE)

add_subdirectory(nvrhi)
target_link_libraries(Dependencies INTERFACE nvrhi)
target_link_libraries(Dependencies INTERFACE nvrhi_vk)
...
```

**Comment by pmrochen** [comment]
You have to declare an instance of vk::DispatchLoaderDynamic somewhere in your .cpp file. 

The simplest way is to use helper macro:
```cpp
//...
VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE;
//...
```

**Comment by casool** [comment]
> You have to declare an instance of vk::DispatchLoaderDynamic somewhere in your .cpp file.
> 
> The simplest way is to use helper macro:
> 
> ```c++
> //...
> VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE;
> //...
> ```

Does nvrhi require me to use the Vulkan C++ bindings? Also, isn't this only necessary if you're building a shared library? It seems nvrhi should automatically do it for you:
https://github.com/NVIDIAGameWorks/nvrhi/blob/a2e059a31b739250fd32edebe0c708c713e475f9/src/vulkan/vulkan-device.cpp#L30

**Comment by pmrochen** [comment]
Unfortunately, by defining:
https://github.com/NVIDIAGameWorks/nvrhi/blob/a2e059a31b739250fd32edebe0c708c713e475f9/src/vulkan/vulkan-backend.h#L32
nvrhi forces you to use C++ dynamic dispatcher, regardless you're building a shared library or not. In reality, it's not always the case, and you should have the ability to enable/disable dynamic dispatcher independently of shared library setting. Also, you should have the ability to issue `VULKAN_HPP_DEFAULT_DISPATCHER.init()` in your code, your way. It looks like we need two new configuration macros to cope with this issue.

**Comment by apanteleev** [comment]
NVRHI will create its own dynamic dispatcher when it's built as a shared library / DLL.
I recently suggested adding an option to do the same when it's built as a static library, with some caveats; see https://github.com/NVIDIAGameWorks/nvrhi/issues/48

**Comment by casool** [comment]
> Unfortunately, by defining:
> 
> https://github.com/NVIDIAGameWorks/nvrhi/blob/a2e059a31b739250fd32edebe0c708c713e475f9/src/vulkan/vulkan-backend.h#L32
> 
> nvrhi forces you to use C++ dynamic dispatcher, regardless you're building a shared library or not. In reality, it's not always the case, and you should have the ability to enable/disable dynamic dispatcher independently of shared library setting. Also, you should have the ability to issue `VULKAN_HPP_DEFAULT_DISPATCHER.init()` in your code, your way. It looks like we need two new configuration macros to cope with this issue.

So is the solution to include the c++ headers in my project?

**Comment by apanteleev** [comment]
Include the vulkan.hpp header and define `VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE` somewhere at global scope. See https://github.com/NVIDIAGameWorks/donut/blob/main/src/app/vulkan/DeviceManager_VK.cpp for an example.

**Comment by casool** [comment]
Thanks!
