### ISSUE TITLE
Seems Redundant loop in CommandList::writeBuffer in Vulkan Backend

### ISSUE THREAD

**Issue by BlurryLight** [NVIDIAGameWorks/nvrhi#52]
https://github.com/NVIDIAGameWorks/nvrhi/blob/970bf530c6b1ad5ec24da8dea468947c297b28e3/src/vulkan/vulkan-buffer.cpp#L434-L440

`thisGulpSize` is rounded up to multiple of 4, so it should be greater equal than  `remaining`.
There should be no second loop here.

`Line 437` is also redundant, because it won't enter this branch if data size greater than 65536

https://github.com/NVIDIAGameWorks/nvrhi/blob/970bf530c6b1ad5ec24da8dea468947c297b28e3/src/vulkan/vulkan-buffer.cpp#L424

**Comment by apanteleev** [comment]
Thanks - I've removed the loop. I think it remained from an early implementation when only updateBuffer was used.
Closing.
