### ISSUE TITLE
Fail to compile nvrhi_d3d12

### ISSUE THREAD

**Issue by hyblocker** [NVIDIAGameWorks/nvrhi#56]
Upon compiling nvrhi_d3d12 using MSVC clang when linked with a C++20 project, I'm hit with this error several times:
```
nvrhi\src\d3d12/d3d12-backend.h(79,62): error : integer value 4294967295 is outside the valid range of values [0, 33554431] for the enumeration type 'D3D12_RESOURCE_STATES' [-Wenum-constexpr-conversion]
```

Replacing `constexpr D3D12_RESOURCE_STATES c_ResourceStateUnknown = D3D12_RESOURCE_STATES(~0u);` on line 79 with `constexpr D3D12_RESOURCE_STATES c_ResourceStateUnknown = D3D12_RESOURCE_STATES(0xFFFFu);` seems to resolve the error.

**Comment by apanteleev** [comment]
Fixed in https://github.com/NVIDIAGameWorks/nvrhi/commit/55b0dd4c2378e36033f16bdda3893dc2b09f9962 - closing.
