### ISSUE TITLE
Recursive locking of a non-recursive mutex can occur in StaticDescriptorHeap

### ISSUE THREAD

**Issue by irtab** [NVIDIAGameWorks/nvrhi#7]
On entry, `StaticDescriptorHeap::allocateDescriptors()` locks `m_Mutex` for the scope of the function, and on descriptor exhaustion (or heavy fragmentation) it calls `Grow()` which also tries to lock `m_Mutex`. However, `m_Mutex` is a `std::mutex`, for which locking multiple times on the same thread is undefined behavior. On Windows Debug builds this generally results in a `std::system_error` being thrown on the second locking attempt, possibly crashing the whole process.

To be fair, I discovered this while writing a buggy app that didn't correctly clean up after itself and would eventually overflow the default RTV heap size of 1024. But still probably worth switching to `std::recursive_mutex` for correctness at least.

**Comment by apanteleev** [comment]
Fixed in https://github.com/NVIDIAGameWorks/nvrhi/commit/f912196034d6de2afb2ed7f8ecd984308445fc51, closing.

Thank you for reporting the issue!
